# Generated by Django 4.2.2 on 2023-06-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=255)),
                ('student_gpa', models.FloatField()),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone_number', models.CharField(max_length=20)),
                ('student_date_of_birth', models.DateField()),
                ('student_year_of_education', models.CharField(max_length=100)),
                ('student_department', models.CharField(max_length=255)),
                ('student_gender', models.BooleanField(choices=[(True, 'Male'), (False, 'Female')])),
                ('student_status', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')])),
            ],
        ),
    ]
